// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJhGdsPWDYmkIC1SZx22Zwo42BF8Sg3cg',
    appId: '1:40383700190:web:95f1f5bc01d7d9a883f64f',
    messagingSenderId: '40383700190',
    projectId: 'semesterplanner-eaf8f',
    authDomain: 'semesterplanner-eaf8f.firebaseapp.com',
    storageBucket: 'semesterplanner-eaf8f.appspot.com',
    measurementId: 'G-Y1NJNX06NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxI4ZhpebdK_SV6uLDeX0HYX1sZdPNoVI',
    appId: '1:40383700190:android:738776a59637a1c383f64f',
    messagingSenderId: '40383700190',
    projectId: 'semesterplanner-eaf8f',
    storageBucket: 'semesterplanner-eaf8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIJBMrfUgmmu1i52agLPw26Q7A0kO2jEs',
    appId: '1:40383700190:ios:a418d9e4e8d757ff83f64f',
    messagingSenderId: '40383700190',
    projectId: 'semesterplanner-eaf8f',
    storageBucket: 'semesterplanner-eaf8f.appspot.com',
    iosBundleId: 'com.example.home',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIJBMrfUgmmu1i52agLPw26Q7A0kO2jEs',
    appId: '1:40383700190:ios:a418d9e4e8d757ff83f64f',
    messagingSenderId: '40383700190',
    projectId: 'semesterplanner-eaf8f',
    storageBucket: 'semesterplanner-eaf8f.appspot.com',
    iosBundleId: 'com.example.home',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJhGdsPWDYmkIC1SZx22Zwo42BF8Sg3cg',
    appId: '1:40383700190:web:c94fadb3c31fa28f83f64f',
    messagingSenderId: '40383700190',
    projectId: 'semesterplanner-eaf8f',
    authDomain: 'semesterplanner-eaf8f.firebaseapp.com',
    storageBucket: 'semesterplanner-eaf8f.appspot.com',
    measurementId: 'G-JKWR6LW87J',
  );

}